Add support for PNG icons and icon packs
WhatAmISupposedToPutHere/tiny-dfr pull request #22
Opened 2023-11-29 11:47 UTC by AdityaGarg8

Icons have also been renamed as per XDG specifications

2023-11-29 12:28 UTC, WhatAmISupposedToPutHere requested changes

2023-11-29 12:28 UTC, WhatAmISupposedToPutHere commented on src/main.rs
> +                // Resize the PNG image to match the specified size
Resize the png on load, not every time right before rendering.

2023-11-29 12:28 UTC, WhatAmISupposedToPutHere commented on src/main.rs
> +                // Iterate over the pixels of the resized PNG image and paint them on the Cairo surface
Cairo supports loading pngs directly

2023-11-29 12:28 UTC, WhatAmISupposedToPutHere commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
This appears to break existing configs.

2023-11-29 13:12 UTC, AdityaGarg8 commented on src/main.rs
> +                // Resize the PNG image to match the specified size
I am simply unable to compile any code when I tried what you meant here.

2023-11-29 13:12 UTC, AdityaGarg8 commented on src/main.rs
> +                // Iterate over the pixels of the resized PNG image and paint them on the Cairo surface
I don't have much idea about this.

2023-11-29 13:13 UTC, AdityaGarg8 commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
Well, this should be fixable. What do you want here then.

2023-11-29 13:14 UTC, AdityaGarg8 commented
I would need help in form of code for PNG, it wasn't easy for me to get it working. Or you could drop the PNG commit.

2023-11-29 13:18 UTC, WhatAmISupposedToPutHere commented on src/main.rs
> +                // Iterate over the pixels of the resized PNG image and paint them on the Cairo surface
https://cairographics.org/manual/cairo-PNG-Support.html

https://docs.rs/cairo-rs/latest/cairo/struct.ImageSurface.html#method.create_from_png

2023-11-29 13:20 UTC, WhatAmISupposedToPutHere commented on src/main.rs
> +                // Resize the PNG image to match the specified size
You can convert the resized buffer into a vec of bytes on load and store that.

2023-11-29 13:34 UTC, AdityaGarg8 commented on src/main.rs
> +                // Resize the PNG image to match the specified size
Still getting plenty of errors. I am still learning rust, so may need help.

2023-11-29 13:43 UTC, AdityaGarg8 commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
For the time being, I can drop the PNG commit, rename the icons as previous. This will make the old config work. Seems good?

2023-11-29 13:46 UTC, WhatAmISupposedToPutHere commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
That looks like it might fix the issue with config backwards compatibility

2023-11-29 13:49 UTC, AdityaGarg8 commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
Ok then. Maybe you could yourself add PNG support, cause its getting difficult for me to improve the code.

2023-11-29 13:50 UTC, WhatAmISupposedToPutHere commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
Is there a reason you want PNG to be supported? All the current icons are svg.

2023-11-29 13:51 UTC, AdityaGarg8 commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
I would like to customize the icons on my touchbar. But the icons I have are in png.

2023-11-29 13:57 UTC, AdityaGarg8 commented on share/tiny-dfr/config.toml
> +    { Icon = "display-brightness-low-symbolic",   Action = "BrightnessDown" },
> Ok then. Maybe you could yourself add PNG support, cause its getting difficult for me to improve the code.

Done and force pushed the branch

2023-11-29 14:03 UTC, WhatAmISupposedToPutHere requested changes

2023-11-29 14:03 UTC, WhatAmISupposedToPutHere commented on src/main.rs
> +        let theme = load_theme();
Why are you re-reading the configs for every button? Read it once and pass it into the button constructor. And i am not sure about IconLoader's api, but you most likely can also initialize it once and pass a constructed object to every button

2023-11-29 14:15 UTC, AdityaGarg8 commented on src/main.rs
> +        let theme = load_theme();
You mean something like this:

```
struct Button {
    image: ButtonImage,
    changed: bool,
    active: bool,
    action: Key,
    theme: Theme,
}
```

2023-11-29 14:17 UTC, WhatAmISupposedToPutHere commented on src/main.rs
> +        let theme = load_theme();
`fn new_svg(icon_name: &str, action: Key, loader: &IconLoader)`

2023-11-29 14:52 UTC, AdityaGarg8 commented on src/main.rs
> +        let theme = load_theme();
Interesting, not as easy as I thought. Will try to get it done if possible for me.

2023-12-02 08:10 UTC, AdityaGarg8 commented
I'll PR again when I get time to fix this.

2023-12-02 08:10 UTC, closed without merging